### PR TITLE
Sign in and sign up

### PR DESCRIPTION
**Pull request by jwo**
Add ability to sign in and sign up the user

boom

### CODE REVIEW

**Comment by jwo** [comment]
@jwo turrble code. Ashamed! :bell:  :bell:  :bell:  shame :bell:  :bell:  :bell:

**Comment by jdmorlan** [comment]
:+1:

**Comment by aliaporci** [comment]
boooo hiss

**Comment by jwo** [comment]
@aliaporci :-1: :100:

**Pull request merged**
